declare var chrome: any
declare var SYCScoring: any
declare var SYCDanmaku: any
declare var SYCSanitize: any
declare var SYCSettings: any
declare var SYCFilter: any
declare var SYCEmoji: any
declare var __SYC_TEST__: any
declare var __SYCContentTest: any
declare var __SYCBackgroundTest: any
